### ISSUE TITLE
Possibly need to update the server.document-root in lighttpd.conf

### ISSUE THREAD

**Issue by kierk** [soltysh/sti-lighttpd#1]
When trying to set this up as is the `http://localhost:8080/` path returns a 404 error.  Looking into it the [blog article](https://blog.openshift.com/create-s2i-builder-image/) is up to date with the correct lighttpd.conf file info.

In this repo the [lighttpd.conf](https://github.com/soltysh/sti-lighttpd/blob/master/etc/lighttpd.conf) has 

> server.document-root = "/opt/openshift/src"

When it should be:

> server.document-root = "/opt/app-root/src"

**Comment by soltysh** [comment]
I've left the old part in master, but new in the [new_base](https://github.com/soltysh/sti-lighttpd/blob/new_base/etc/lighttpd.conf) branch. Since the article was updated I should probably update master. Thanks for pointing it out!

**Comment by soltysh** [comment]
I've merged the aforementioned branch into master. I've also cleaned and updated the code. Should be good now. Thanks again!

**Comment by kierk** [comment]
No problem - thanks for the great code example!
